const fs=require('fs');
const crypto=require('crypto');
const serverPath='server.js';
let s=fs.readFileSync(serverPath,'utf8');
const dbMarker='CREATE TABLE IF NOT EXISTS exam_attempts(id SERIAL PRIMARY KEY,quiz_id INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,started_at TIMESTAMPTZ DEFAULT NOW());`);';
const dbInsert=dbMarker+'await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT");await pool.query("CREATE TABLE IF NOT EXISTS password_reset_tokens(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())");if(process.env.TEACHER_EMAIL&&process.env.TEACHER_USERNAME){await pool.query("UPDATE users SET email=$1 WHERE username=$2 AND role='teacher'",[String(process.env.TEACHER_EMAIL).trim().toLowerCase(),String(process.env.TEACHER_USERNAME).trim().toLowerCase()])}';
if(s.includes(dbMarker)&&!s.includes('password_reset_tokens'))s=s.replace(dbMarker,dbInsert);
const authMarker='app.post("/api/auth/register"';
const resetRoutes=`async function sendResetEmail(to,link){if(!process.env.RESEND_API_KEY||!process.env.RESEND_FROM)throw Error("Password reset email service is not configured");const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:"Bearer "+process.env.RESEND_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({from:process.env.RESEND_FROM,to:[to],subject:"QuizMaster password reset",html:\`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto"><h2>QuizMaster password reset</h2><p>A password reset was requested for your teacher account.</p><p><a href="\${link}" style="display:inline-block;background:#1565c0;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none">Reset password</a></p><p>This link expires in 30 minutes. If you did not request this, you can ignore this email.</p></div>\`})});if(!r.ok)throw Error("Email delivery failed")}
app.post("/api/auth/forgot-password",async(req,res)=>{const email=String(req.body.email||"").trim().toLowerCase();if(!email)return res.status(400).json({error:"Email is required"});try{const u=(await pool.query("SELECT id,email FROM users WHERE role='teacher' AND lower(email)=lower($1) LIMIT 1",[email])).rows[0];if(u){const raw=crypto.randomBytes(32).toString("hex"),th=crypto.createHash("sha256").update(raw).digest("hex");await pool.query("DELETE FROM password_reset_tokens WHERE user_id=$1 OR expires_at<=NOW()",[u.id]);await pool.query("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 minutes')",[u.id,th]);const base=String(process.env.APP_BASE_URL||"").replace(/\\/$/,"");if(!base)throw Error("APP_BASE_URL is not configured");await sendResetEmail(u.email,base+"/reset-password.html?token="+raw)}res.json({ok:true,message:"If that email belongs to a teacher account, a password reset link has been sent."})}catch(e){console.error(e);res.status(500).json({error:"Unable to send password reset email"})}});
app.post("/api/auth/reset-password",async(req,res)=>{const token=String(req.body.token||"").trim(),password=String(req.body.password||"");if(!token||password.length<6)return res.status(400).json({error:"A valid reset token and a password of at least 6 characters are required"});try{const h=crypto.createHash("sha256").update(token).digest("hex"),r=await pool.query("SELECT user_id FROM password_reset_tokens WHERE token_hash=$1 AND expires_at>NOW()",[h]);if(!r.rows.length)return res.status(400).json({error:"This reset link is invalid or expired"});const userId=r.rows[0].user_id;await pool.query("UPDATE users SET password_hash=$1 WHERE id=$2 AND role='teacher'",[await hashPassword(password),userId]);await pool.query("DELETE FROM password_reset_tokens WHERE user_id=$1",[userId]);await pool.query("DELETE FROM sessions WHERE user_id=$1",[userId]);res.json({ok:true,message:"Password changed successfully. Please sign in again."})}catch(e){console.error(e);res.status(500).json({error:"Password reset failed"})}});
`;
if(!s.includes('/api/auth/forgot-password')){if(!s.includes(authMarker))throw Error('Auth route marker not found');s=s.replace(authMarker,resetRoutes+authMarker)}
fs.writeFileSync(serverPath,s);
const page='reset-password.html';
if(!fs.existsSync(page))fs.writeFileSync(page,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reset QuizMaster Password</title><style>body{margin:0;background:#f5f8fc;font-family:Arial,sans-serif;color:#17324d}.card{max-width:420px;margin:10vh auto;background:#fff;border:1px solid #e2eaf3;border-radius:16px;padding:24px;box-shadow:0 2px 10px rgba(15,50,90,.06)}h1{text-align:center}label{display:block;font-size:12px;font-weight:700;color:#6b7c93;margin:14px 0 6px}input{width:100%;box-sizing:border-box;border:1px solid #d7e1ed;border-radius:10px;padding:12px}button{width:100%;margin-top:18px;padding:12px;border:0;border-radius:10px;background:#1565c0;color:#fff;font-weight:700;cursor:pointer}.msg{margin-top:14px;font-size:13px}.ok{color:#168457}.err{color:#b42318}</style></head><body><div class="card"><h1>QuizMaster</h1><p style="text-align:center">Set a new teacher password</p><label>NEW PASSWORD</label><input id="p1" type="password" minlength="6" autocomplete="new-password"><label>CONFIRM PASSWORD</label><input id="p2" type="password" minlength="6" autocomplete="new-password"><button onclick="resetPassword()">Change Password</button><div id="msg" class="msg"></div></div><script>async function resetPassword(){const msg=document.getElementById('msg'),p1=document.getElementById('p1').value,p2=document.getElementById('p2').value,token=new URLSearchParams(location.search).get('token')||'';msg.className='msg';if(!token)return msg.textContent='This reset link is missing its token.';if(p1.length<6)return msg.textContent='Password must be at least 6 characters.';if(p1!==p2)return msg.textContent='Passwords do not match.';try{const r=await fetch('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password:p1})});const d=await r.json();if(!r.ok)throw Error(d.error||'Reset failed');msg.className='msg ok';msg.textContent=d.message||'Password changed successfully.';setTimeout(()=>location.href='/',1500)}catch(e){msg.className='msg err';msg.textContent=e.message}}</script></body></html>`);
const index='index.html';let h=fs.readFileSync(index,'utf8');if(!h.includes('forgot-password-ui')){const marker='<button class="btn primary" style="width:100%" onclick="login()">Sign in</button><p id="loginError"';const replacement='<button class="btn primary" style="width:100%" onclick="login()">Sign in</button><button id="forgot-password-ui" class="btn outline" style="width:100%;margin-top:10px" type="button" onclick="showForgotPassword()">Forgot password?</button><p id="loginError"';if(!h.includes(marker))throw Error('Login button marker not found');h=h.replace(marker,replacement);h=h.replace('</body>','<script>function showForgotPassword(){const e=prompt("Enter the email address linked to the teacher account:");if(!e)return;fetch("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:e.trim()})}).then(async r=>{const d=await r.json();alert(d.message||d.error||"Request complete")}).catch(()=>alert("Unable to send password reset email."))}</script></body>');fs.writeFileSync(index,h)}
