const fs=require('fs');
const crypto=require('crypto');
const serverPath='server.js';
let s=fs.readFileSync(serverPath,'utf8');

const classMarker='await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS class_level INTEGER");';
if(!s.includes('password_reset_tokens')){
  if(!s.includes(classMarker))throw Error('Password reset database marker not found');
  s=s.replace(classMarker,classMarker+'await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT");await pool.query("CREATE TABLE IF NOT EXISTS password_reset_tokens(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())");',1);
}

const resetRoutes=`async function sendResetEmail(to,link){const key=process.env.RESEND_API_KEY;const from=process.env.RESEND_FROM||'QuizMaster <onboarding@resend.dev>';if(!key)throw Error('RESEND_API_KEY is not configured');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json','User-Agent':'QuizMaster/1.0'},body:JSON.stringify({from,to:[to],subject:'QuizMaster teacher password reset',html:'<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#17324d"><h2>QuizMaster password reset</h2><p>A password reset was requested for your teacher account.</p><p><a href="'+link+'" style="display:inline-block;background:#1565c0;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none">Reset password</a></p><p>This link expires in 30 minutes and can be used only once.</p><p>If you did not request this, you can safely ignore this email.</p></div>'})});if(!r.ok){const body=await r.text().catch(()=> '');console.error('Resend error:',r.status,body);throw Error('Email delivery failed')}}
app.post('/api/auth/forgot-password',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase();if(!email)return res.status(400).json({error:'Email is required'});try{const u=(await pool.query("SELECT id,email FROM users WHERE role='teacher' AND lower(email)=lower($1) LIMIT 1",[email])).rows[0];if(u?.email){const raw=crypto.randomBytes(32).toString('hex'),th=crypto.createHash('sha256').update(raw).digest('hex');await pool.query('DELETE FROM password_reset_tokens WHERE user_id=$1 OR expires_at<=NOW()',[u.id]);await pool.query("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 minutes')",[u.id,th]);const base=String(process.env.APP_BASE_URL||process.env.RENDER_EXTERNAL_URL||'').replace(/\\/$/,'');if(!base)throw Error('APP_BASE_URL/RENDER_EXTERNAL_URL is not configured');await sendResetEmail(u.email,base+'/reset-password.html?token='+raw)}res.json({ok:true,message:'If that email belongs to a teacher account, a password reset link has been sent.'})}catch(e){console.error('Password reset request failed:',e.message);res.json({ok:true,message:'If that email belongs to a teacher account, a password reset link has been sent.'})}});
app.post('/api/auth/reset-password',async(req,res)=>{const token=String(req.body.token||'').trim(),password=String(req.body.password||'');if(!token||password.length<6)return res.status(400).json({error:'A valid reset token and a password of at least 6 characters are required'});try{const h=crypto.createHash('sha256').update(token).digest('hex'),r=await pool.query('SELECT user_id FROM password_reset_tokens WHERE token_hash=$1 AND expires_at>NOW()',[h]);if(!r.rows.length)return res.status(400).json({error:'This reset link is invalid or expired'});const userId=r.rows[0].user_id;const changed=await pool.query("UPDATE users SET password_hash=$1 WHERE id=$2 AND role='teacher' RETURNING id",[await hashPassword(password),userId]);if(!changed.rows.length)return res.status(400).json({error:'This reset link is invalid or expired'});await pool.query('DELETE FROM password_reset_tokens WHERE user_id=$1',[userId]);await pool.query('DELETE FROM sessions WHERE user_id=$1',[userId]);res.json({ok:true,message:'Password changed successfully. Please sign in again.'})}catch(e){console.error('Password reset failed:',e);res.status(500).json({error:'Password reset failed'})}});\n`;

if(!s.includes('/api/auth/forgot-password')){
  const markers=['app.post("/api/auth/register"','app.post("/api/auth/login"','app.get("/api/health"'];
  const marker=markers.find(x=>s.includes(x));
  if(!marker)throw Error('Auth route marker not found');
  s=s.replace(marker,resetRoutes+marker,1);
}
fs.writeFileSync(serverPath,s);

if(!fs.existsSync('reset-password.html'))fs.writeFileSync('reset-password.html','<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reset QuizMaster Password</title></head><body><main><h1>QuizMaster</h1><p>Set a new teacher password</p><input id="p1" type="password" minlength="6" placeholder="New password"><input id="p2" type="password" minlength="6" placeholder="Confirm password"><button onclick="resetPassword()">Change Password</button><p id="msg"></p></main><script>async function resetPassword(){const msg=document.getElementById("msg"),p1=document.getElementById("p1").value,p2=document.getElementById("p2").value,token=new URLSearchParams(location.search).get("token")||"";if(!token)return msg.textContent="This reset link is missing its token.";if(p1.length<6)return msg.textContent="Password must be at least 6 characters.";if(p1!==p2)return msg.textContent="Passwords do not match.";try{const r=await fetch("/api/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password:p1})}),d=await r.json();msg.textContent=d.message||d.error||"Done";if(r.ok)setTimeout(()=>location.href="/",1500)}catch(e){msg.textContent="Unable to reset password."}}</script></body></html>');
if(!fs.existsSync('forgot-password.html'))fs.writeFileSync('forgot-password.html','<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Forgot QuizMaster Password</title></head><body><main><h1>QuizMaster</h1><p>Reset your teacher password</p><input id="email" type="email" placeholder="Teacher email"><button onclick="sendReset()">Send Reset Link</button><p id="msg"></p><a href="/">Back to sign in</a></main><script>async function sendReset(){const msg=document.getElementById("msg"),email=document.getElementById("email").value.trim();if(!email)return msg.textContent="Please enter your email address.";try{const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})}),d=await r.json();msg.textContent=d.message||d.error||"Done"}catch(e){msg.textContent="Unable to process the request."}}</script></body></html>');

let h=fs.readFileSync('index.html','utf8');
if(!h.includes('forgot-password-ui')){
  const loginMarker='<button class="btn primary" style="width:100%" onclick="login()">Sign in</button>';
  if(!h.includes(loginMarker))throw Error('Login button marker not found');
  h=h.replace(loginMarker,loginMarker+'<a id="forgot-password-ui" href="/forgot-password.html" style="display:block;text-align:center;margin-top:12px;color:#1565c0;text-decoration:none;font-size:13px">Forgot password?</a>',1);
  fs.writeFileSync('index.html',h);
}
console.log('QuizMaster password reset patch applied');
