const fs=require('fs');
const crypto=require('crypto');
const serverPath='server.js';
let s=fs.readFileSync(serverPath,'utf8');

const dbMarker='CREATE TABLE IF NOT EXISTS exam_attempts(id SERIAL PRIMARY KEY,quiz_id INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,started_at TIMESTAMPTZ DEFAULT NOW());`);';
const dbInsert=dbMarker+'await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT");await pool.query("CREATE TABLE IF NOT EXISTS password_reset_tokens(id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())");if(process.env.TEACHER_EMAIL&&process.env.TEACHER_USERNAME){await pool.query("UPDATE users SET email=$1 WHERE username=$2 AND role='teacher'",[String(process.env.TEACHER_EMAIL).trim().toLowerCase(),String(process.env.TEACHER_USERNAME).trim().toLowerCase()])}';
if(s.includes(dbMarker)&&!s.includes('password_reset_tokens'))s=s.replace(dbMarker,dbInsert);

const authMarker='app.post("/api/auth/register"';
const resetRoutes=`async function sendResetEmail(to,link){const key=process.env.RESEND_API_KEY;const from=process.env.RESEND_FROM||'QuizMaster <onboarding@resend.dev>';if(!key)throw Error('RESEND_API_KEY is not configured');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json','User-Agent':'QuizMaster/1.0'},body:JSON.stringify({from,to:[to],subject:'QuizMaster teacher password reset',html:\`<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#17324d"><h2>QuizMaster password reset</h2><p>A password reset was requested for your teacher account.</p><p><a href="\${link}" style="display:inline-block;background:#1565c0;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none">Reset password</a></p><p>This link expires in 30 minutes and can be used only once.</p><p>If you did not request this, you can safely ignore this email.</p></div>\`})});if(!r.ok){const body=await r.text().catch(()=> '');console.error('Resend error:',r.status,body);throw Error('Email delivery failed')}}
app.post('/api/auth/forgot-password',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase();if(!email)return res.status(400).json({error:'Email is required'});try{const u=(await pool.query("SELECT id,email FROM users WHERE role='teacher' AND lower(email)=lower($1) LIMIT 1",[email])).rows[0];if(u?.email){const raw=crypto.randomBytes(32).toString('hex'),th=crypto.createHash('sha256').update(raw).digest('hex');await pool.query('DELETE FROM password_reset_tokens WHERE user_id=$1 OR expires_at<=NOW()',[u.id]);await pool.query("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 minutes')",[u.id,th]);const base=String(process.env.APP_BASE_URL||process.env.RENDER_EXTERNAL_URL||'').replace(/\\/$/,'');if(!base)throw Error('APP_BASE_URL/RENDER_EXTERNAL_URL is not configured');await sendResetEmail(u.email,base+'/reset-password.html?token='+raw)}res.json({ok:true,message:'If that email belongs to a teacher account, a password reset link has been sent.'})}catch(e){console.error('Password reset request failed:',e.message);res.json({ok:true,message:'If that email belongs to a teacher account, a password reset link has been sent.'})}});
app.post('/api/auth/reset-password',async(req,res)=>{const token=String(req.body.token||'').trim(),password=String(req.body.password||'');if(!token||password.length<6)return res.status(400).json({error:'A valid reset token and a password of at least 6 characters are required'});try{const h=crypto.createHash('sha256').update(token).digest('hex'),r=await pool.query('SELECT user_id FROM password_reset_tokens WHERE token_hash=$1 AND expires_at>NOW()',[h]);if(!r.rows.length)return res.status(400).json({error:'This reset link is invalid or expired'});const userId=r.rows[0].user_id;const changed=await pool.query("UPDATE users SET password_hash=$1 WHERE id=$2 AND role='teacher' RETURNING id",[await hashPassword(password),userId]);if(!changed.rows.length)return res.status(400).json({error:'This reset link is invalid or expired'});await pool.query('DELETE FROM password_reset_tokens WHERE user_id=$1',[userId]);await pool.query('DELETE FROM sessions WHERE user_id=$1',[userId]);res.json({ok:true,message:'Password changed successfully. Please sign in again.'})}catch(e){console.error('Password reset failed:',e);res.status(500).json({error:'Password reset failed'})}});
`;
if(!s.includes('/api/auth/forgot-password')){if(!s.includes(authMarker))throw Error('Auth route marker not found');s=s.replace(authMarker,resetRoutes+authMarker)}
fs.writeFileSync(serverPath,s);

if(!fs.existsSync('reset-password.html'))fs.writeFileSync('reset-password.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reset QuizMaster Password</title><style>body{margin:0;background:#f5f8fc;font-family:Arial,sans-serif;color:#17324d}.card{max-width:420px;margin:9vh auto;background:#fff;border:1px solid #e2eaf3;border-radius:16px;padding:24px;box-shadow:0 2px 10px rgba(15,50,90,.06)}h1{text-align:center;margin:0 0 6px}.muted{text-align:center;color:#6b7c93}label{display:block;font-size:12px;font-weight:700;color:#6b7c93;margin:16px 0 6px}input{width:100%;box-sizing:border-box;border:1px solid #d7e1ed;border-radius:10px;padding:12px}button{width:100%;margin-top:18px;padding:12px;border:0;border-radius:10px;background:#1565c0;color:#fff;font-weight:700;cursor:pointer}.msg{margin-top:14px;font-size:13px;text-align:center}.ok{color:#168457}.err{color:#b42318}</style></head><body><div class="card"><h1>QuizMaster</h1><p class="muted">Set a new teacher password</p><label>NEW PASSWORD</label><input id="p1" type="password" minlength="6" autocomplete="new-password"><label>CONFIRM PASSWORD</label><input id="p2" type="password" minlength="6" autocomplete="new-password"><button onclick="resetPassword()">Change Password</button><div id="msg" class="msg"></div></div><script>async function resetPassword(){const msg=document.getElementById('msg'),p1=document.getElementById('p1').value,p2=document.getElementById('p2').value,token=new URLSearchParams(location.search).get('token')||'';msg.className='msg';if(!token){msg.className='msg err';return msg.textContent='This reset link is missing its token.'}if(p1.length<6){msg.className='msg err';return msg.textContent='Password must be at least 6 characters.'}if(p1!==p2){msg.className='msg err';return msg.textContent='Passwords do not match.'}try{const r=await fetch('/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password:p1})});const d=await r.json();if(!r.ok)throw Error(d.error||'Reset failed');msg.className='msg ok';msg.textContent=d.message||'Password changed successfully.';setTimeout(()=>location.href='/',1500)}catch(e){msg.className='msg err';msg.textContent=e.message}}</script></body></html>`);

if(!fs.existsSync('forgot-password.html'))fs.writeFileSync('forgot-password.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Forgot QuizMaster Password</title><style>body{margin:0;background:#f5f8fc;font-family:Arial,sans-serif;color:#17324d}.card{max-width:420px;margin:9vh auto;background:#fff;border:1px solid #e2eaf3;border-radius:16px;padding:24px;box-shadow:0 2px 10px rgba(15,50,90,.06)}h1{text-align:center;margin:0 0 6px}.muted{text-align:center;color:#6b7c93}label{display:block;font-size:12px;font-weight:700;color:#6b7c93;margin:16px 0 6px}input{width:100%;box-sizing:border-box;border:1px solid #d7e1ed;border-radius:10px;padding:12px}button{width:100%;margin-top:18px;padding:12px;border:0;border-radius:10px;background:#1565c0;color:#fff;font-weight:700;cursor:pointer}.back{display:block;text-align:center;margin-top:14px;color:#1565c0;text-decoration:none;font-size:13px}.msg{margin-top:14px;font-size:13px;text-align:center}.ok{color:#168457}.err{color:#b42318}</style></head><body><div class="card"><h1>QuizMaster</h1><p class="muted">Reset your teacher dashboard password</p><label>TEACHER EMAIL</label><input id="email" type="email" autocomplete="email" placeholder="you@example.com"><button onclick="sendReset()">Send Reset Link</button><div id="msg" class="msg"></div><a class="back" href="/">← Back to sign in</a></div><script>async function sendReset(){const msg=document.getElementById('msg'),email=document.getElementById('email').value.trim();msg.className='msg';if(!email){msg.className='msg err';return msg.textContent='Please enter your email address.'}try{const r=await fetch('/api/auth/forgot-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json();msg.className='msg ok';msg.textContent=d.message||'If that email belongs to a teacher account, a reset link has been sent.'}catch(e){msg.className='msg err';msg.textContent='Unable to process the request. Please try again.'}}</script></body></html>`);

let h=fs.readFileSync('index.html','utf8');if(!h.includes('forgot-password-ui')){const marker='<button class="btn primary" style="width:100%" onclick="login()">Sign in</button><p id="loginError"';const replacement='<button class="btn primary" style="width:100%" onclick="login()">Sign in</button><a id="forgot-password-ui" href="/forgot-password.html" style="display:block;text-align:center;margin-top:12px;color:#1565c0;text-decoration:none;font-size:13px">Forgot password?</a><p id="loginError"';if(!h.includes(marker))throw Error('Login button marker not found');h=h.replace(marker,replacement);fs.writeFileSync('index.html',h)}
